"""
Local dataset of REAL books for Book Nook 📚

Constraints:
- No external APIs
- No generated titles
- Expandable: just append dicts to BOOKS
"""

from typing import List, Dict


BOOKS: List[Dict] = [
    # Classics
    {
        "title": "Pride and Prejudice",
        "author": "Jane Austen",
        "genres": ["classics", "romance"],
        "keywords": ["love", "society", "family", "marriage", "wit"],
        "description": "Elizabeth Bennet navigates manners, misunderstandings, and love in Regency England.",
    },
    {
        "title": "Jane Eyre",
        "author": "Charlotte Brontë",
        "genres": ["classics", "romance"],
        "keywords": ["love", "identity", "gothic", "independence"],
        "description": "An orphaned governess seeks belonging and integrity while falling for the enigmatic Mr. Rochester.",
    },
    {
        "title": "Wuthering Heights",
        "author": "Emily Brontë",
        "genres": ["classics"],
        "keywords": ["revenge", "love", "gothic", "obsession"],
        "description": "A stormy tale of passion and vengeance on the Yorkshire moors.",
    },
    {
        "title": "1984",
        "author": "George Orwell",
        "genres": ["classics", "sci-fi", "dystopia"],
        "keywords": ["dystopia", "totalitarianism", "surveillance", "rebellion"],
        "description": "In a world of constant surveillance, Winston Smith wrestles with truth and freedom.",
    },
    {
        "title": "Animal Farm",
        "author": "George Orwell",
        "genres": ["classics"],
        "keywords": ["politics", "satire", "power", "revolution"],
        "description": "A farm’s revolution becomes a sharp satire of power and propaganda.",
    },
    {
        "title": "To Kill a Mockingbird",
        "author": "Harper Lee",
        "genres": ["classics", "ya"],
        "keywords": ["justice", "racism", "family", "coming-of-age"],
        "description": "Scout Finch watches her father defend an innocent man in the segregated American South.",
    },
    {
        "title": "The Great Gatsby",
        "author": "F. Scott Fitzgerald",
        "genres": ["classics"],
        "keywords": ["wealth", "illusion", "love", "american dream"],
        "description": "A dazzling portrait of longing and excess in the Jazz Age.",
    },
    {
        "title": "Moby-Dick",
        "author": "Herman Melville",
        "genres": ["classics", "adventure"],
        "keywords": ["sea", "obsession", "revenge", "whaling"],
        "description": "Captain Ahab’s relentless pursuit of the white whale becomes an epic of obsession.",
    },
    {
        "title": "The Catcher in the Rye",
        "author": "J. D. Salinger",
        "genres": ["classics", "ya"],
        "keywords": ["coming-of-age", "identity", "alienation"],
        "description": "Holden Caulfield wanders New York, wrestling with grief and growing up.",
    },
    {
        "title": "The Picture of Dorian Gray",
        "author": "Oscar Wilde",
        "genres": ["classics", "horror"],
        "keywords": ["vanity", "morality", "gothic", "art"],
        "description": "A young man’s portrait bears the cost of his choices as he remains outwardly unchanged.",
    },
    {
        "title": "Frankenstein",
        "author": "Mary Shelley",
        "genres": ["classics", "horror", "sci-fi"],
        "keywords": ["science", "creation", "isolation", "ethics"],
        "description": "A scientist’s ambition leads to a creation that challenges responsibility and humanity.",
    },
    {
        "title": "Dracula",
        "author": "Bram Stoker",
        "genres": ["classics", "horror"],
        "keywords": ["vampires", "gothic", "fear", "friendship"],
        "description": "A band of allies confronts a terrifying vampire in a battle of will and survival.",
    },
    {
        "title": "The Hobbit",
        "author": "J. R. R. Tolkien",
        "genres": ["fantasy", "classics", "adventure"],
        "keywords": ["dragons", "journey", "friendship", "courage"],
        "description": "Bilbo Baggins is swept into an adventure to reclaim a treasure guarded by a dragon.",
    },
    {
        "title": "The Fellowship of the Ring",
        "author": "J. R. R. Tolkien",
        "genres": ["fantasy", "classics", "adventure"],
        "keywords": ["friendship", "quest", "magic", "war"],
        "description": "A fellowship begins a perilous quest to destroy a powerful ring.",
    },
    {
        "title": "The Two Towers",
        "author": "J. R. R. Tolkien",
        "genres": ["fantasy", "classics", "adventure"],
        "keywords": ["war", "friendship", "quest", "courage"],
        "description": "Allies are scattered as war rises and hope hangs by a thread.",
    },
    {
        "title": "The Return of the King",
        "author": "J. R. R. Tolkien",
        "genres": ["fantasy", "classics", "adventure"],
        "keywords": ["war", "quest", "friendship", "destiny"],
        "description": "The final struggle for Middle‑earth culminates as the ringbearer nears Mount Doom.",
    },

    # Fantasy
    {
        "title": "A Wizard of Earthsea",
        "author": "Ursula K. Le Guin",
        "genres": ["fantasy", "classics", "ya"],
        "keywords": ["magic", "identity", "dragons", "coming-of-age"],
        "description": "A gifted boy learns wizardry—and the cost of pride—on the archipelago of Earthsea.",
    },
    {
        "title": "The Name of the Wind",
        "author": "Patrick Rothfuss",
        "genres": ["fantasy"],
        "keywords": ["magic", "music", "adventure", "myth"],
        "description": "Kvothe recounts his life story, from gifted child to notorious legend.",
    },
    {
        "title": "Mistborn: The Final Empire",
        "author": "Brandon Sanderson",
        "genres": ["fantasy"],
        "keywords": ["heist", "magic", "rebellion", "empire"],
        "description": "A crew of thieves plots to overthrow an immortal tyrant using a unique metal-based magic.",
    },
    {
        "title": "The Way of Kings",
        "author": "Brandon Sanderson",
        "genres": ["fantasy"],
        "keywords": ["war", "honor", "destiny", "magic"],
        "description": "Lives collide on a shattered world as ancient powers begin to return.",
    },
    {
        "title": "The Lies of Locke Lamora",
        "author": "Scott Lynch",
        "genres": ["fantasy"],
        "keywords": ["heist", "friendship", "con artists", "crime"],
        "description": "A master thief and his gang run elaborate schemes in a city of canals and danger.",
    },
    {
        "title": "Good Omens",
        "author": "Terry Pratchett & Neil Gaiman",
        "genres": ["fantasy", "humor"],
        "keywords": ["friendship", "angels", "demons", "apocalypse", "comedy"],
        "description": "An angel and a demon team up to prevent the apocalypse—mostly because they like Earth.",
    },
    {
        "title": "The Princess Bride",
        "author": "William Goldman",
        "genres": ["fantasy", "romance", "humor"],
        "keywords": ["love", "adventure", "fairy tale", "comedy"],
        "description": "A swashbuckling tale of true love, revenge, and very memorable swordsmen.",
    },

    # Sci‑Fi / Dystopia
    {
        "title": "Dune",
        "author": "Frank Herbert",
        "genres": ["sci-fi", "classics"],
        "keywords": ["desert", "politics", "prophecy", "war"],
        "description": "On a desert planet, Paul Atreides becomes entangled in power, ecology, and destiny.",
    },
    {
        "title": "The Left Hand of Darkness",
        "author": "Ursula K. Le Guin",
        "genres": ["sci-fi", "classics"],
        "keywords": ["politics", "gender", "friendship", "winter"],
        "description": "An envoy navigates a frozen world and forms a bond that reshapes his understanding of humanity.",
    },
    {
        "title": "The Handmaid's Tale",
        "author": "Margaret Atwood",
        "genres": ["dystopia", "classics"],
        "keywords": ["dystopia", "women", "power", "rebellion"],
        "description": "In a theocratic regime, Offred fights to hold onto her identity and memory.",
    },
    {
        "title": "Fahrenheit 451",
        "author": "Ray Bradbury",
        "genres": ["dystopia", "classics", "sci-fi"],
        "keywords": ["books", "censorship", "rebellion", "society"],
        "description": "A fireman tasked with burning books begins to question the world he serves.",
    },
    {
        "title": "Brave New World",
        "author": "Aldous Huxley",
        "genres": ["dystopia", "classics", "sci-fi"],
        "keywords": ["dystopia", "society", "control", "technology"],
        "description": "A polished future of engineered happiness hides a chilling cost.",
    },
    {
        "title": "The Martian",
        "author": "Andy Weir",
        "genres": ["sci-fi"],
        "keywords": ["survival", "space", "science", "humor"],
        "description": "Stranded on Mars, an astronaut science-hacks his way toward survival and rescue.",
    },
    {
        "title": "Ender's Game",
        "author": "Orson Scott Card",
        "genres": ["sci-fi", "ya"],
        "keywords": ["war", "strategy", "children", "space"],
        "description": "A brilliant child is trained in a battle school to confront an alien threat.",
    },
    {
        "title": "Neuromancer",
        "author": "William Gibson",
        "genres": ["sci-fi"],
        "keywords": ["cyberpunk", "ai", "hacking", "crime"],
        "description": "A washed-up hacker is hired for a high‑stakes job in a gritty cyberpunk future.",
    },

    # Mystery / Thriller
    {
        "title": "The Hound of the Baskervilles",
        "author": "Arthur Conan Doyle",
        "genres": ["mystery", "classics"],
        "keywords": ["detective", "investigation", "legend", "fog"],
        "description": "Sherlock Holmes investigates a chilling curse on the moors.",
    },
    {
        "title": "Murder on the Orient Express",
        "author": "Agatha Christie",
        "genres": ["mystery", "classics"],
        "keywords": ["detective", "train", "whodunit", "justice"],
        "description": "Hercule Poirot solves a murder aboard a snowbound luxury train.",
    },
    {
        "title": "The Girl with the Dragon Tattoo",
        "author": "Stieg Larsson",
        "genres": ["mystery", "thriller"],
        "keywords": ["investigation", "family secrets", "journalism", "crime"],
        "description": "A journalist and a hacker uncover dark secrets while investigating a decades-old disappearance.",
    },

    # Romance
    {
        "title": "The Notebook",
        "author": "Nicholas Sparks",
        "genres": ["romance"],
        "keywords": ["love", "memory", "family"],
        "description": "A lifelong love story told through letters, time, and devotion.",
    },
    {
        "title": "Me Before You",
        "author": "Jojo Moyes",
        "genres": ["romance"],
        "keywords": ["love", "caregiving", "choices", "family"],
        "description": "A young woman becomes a caretaker and finds her life transformed by an unexpected relationship.",
    },

    # YA
    {
        "title": "The Hunger Games",
        "author": "Suzanne Collins",
        "genres": ["ya", "dystopia"],
        "keywords": ["dystopia", "survival", "rebellion", "war"],
        "description": "Katniss Everdeen fights for survival in a brutal televised competition.",
    },
    {
        "title": "Harry Potter and the Sorcerer's Stone",
        "author": "J. K. Rowling",
        "genres": ["fantasy", "ya"],
        "keywords": ["magic", "friendship", "school", "adventure"],
        "description": "A boy discovers he’s a wizard and begins a new life at Hogwarts School of Witchcraft and Wizardry.",
    },
    {
        "title": "The Fault in Our Stars",
        "author": "John Green",
        "genres": ["ya", "romance"],
        "keywords": ["love", "friendship", "illness", "grief"],
        "description": "Two teens form a deep bond while facing illness, humor, and heartbreak.",
    },

    # Non‑fiction / Self‑help
    {
        "title": "Sapiens: A Brief History of Humankind",
        "author": "Yuval Noah Harari",
        "genres": ["non-fiction"],
        "keywords": ["history", "society", "evolution", "culture"],
        "description": "A sweeping look at human history, from ancient ancestors to modern societies.",
    },
    {
        "title": "Educated",
        "author": "Tara Westover",
        "genres": ["non-fiction", "memoir"],
        "keywords": ["memoir", "family", "education", "identity"],
        "description": "A memoir of growing up in a survivalist family and discovering education as a path forward.",
    },
    {
        "title": "Atomic Habits",
        "author": "James Clear",
        "genres": ["self-help", "non-fiction"],
        "keywords": ["habits", "psychology", "productivity", "change"],
        "description": "A practical guide to building good habits and breaking bad ones through small, consistent changes.",
    },
    {
        "title": "The Power of Habit",
        "author": "Charles Duhigg",
        "genres": ["non-fiction", "self-help"],
        "keywords": ["habits", "psychology", "behavior", "change"],
        "description": "An exploration of how habits work—and how they can be transformed.",
    },
    {
        "title": "Thinking, Fast and Slow",
        "author": "Daniel Kahneman",
        "genres": ["non-fiction", "psychology"],
        "keywords": ["psychology", "decision-making", "bias", "behavior"],
        "description": "A tour of two modes of thinking and the biases that shape our decisions.",
    },

    {
        "title": "Great Expectations",
        "author": "Charles Dickens",
        "genres": ["classics", "fiction"],
        "keywords": ["coming-of-age", "wealth", "society", "love"],
        "description": "An orphan named Pip comes into unexpected wealth and navigates Victorian society.",
    },
    {
        "title": "Sense and Sensibility",
        "author": "Jane Austen",
        "genres": ["classics", "romance"],
        "keywords": ["sisters", "love", "society", "marriage"],
        "description": "Two sisters navigate love and heartbreak with differing approaches of reason and emotion.",
    },
    {
        "title": "Little Women",
        "author": "Louisa May Alcott",
        "genres": ["classics", "ya", "fiction"],
        "keywords": ["sisters", "family", "coming-of-age", "love"],
        "description": "Four sisters grow, learn, and love in Civil War-era America.",
    },
    {
        "title": "Crime and Punishment",
        "author": "Fyodor Dostoevsky",
        "genres": ["classics", "thriller", "psychology"],
        "keywords": ["guilt", "morality", "murder", "redemption"],
        "description": "A destitute student wrestles with extreme guilt and paranoia after committing a terrible crime.",
    },
    {
        "title": "Les Misérables",
        "author": "Victor Hugo",
        "genres": ["classics", "historical", "fiction"],
        "keywords": ["redemption", "revolution", "justice", "love"],
        "description": "An ex-convict seeks a new life amidst the struggles of 19th-century France.",
    },
    {
        "title": "A Tale of Two Cities",
        "author": "Charles Dickens",
        "genres": ["classics", "historical"],
        "keywords": ["revolution", "sacrifice", "paris", "london"],
        "description": "Two men are caught up in the madness and bloodshed of the French Revolution.",
    },
    {
        "title": "The Eye of the World",
        "author": "Robert Jordan",
        "genres": ["fantasy", "adventure"],
        "keywords": ["magic", "destiny", "quest", "good vs evil"],
        "description": "Young villagers flee their home as they discover their connection to a world-altering destiny.",
    },
    {
        "title": "Assassin's Apprentice",
        "author": "Robin Hobb",
        "genres": ["fantasy", "fiction"],
        "keywords": ["assassins", "magic", "royalty", "coming-of-age"],
        "description": "A royal bastard is trained in the shadow arts of assassination to protect his kingdom.",
    },
    {
        "title": "The Fifth Season",
        "author": "N. K. Jemisin",
        "genres": ["fantasy", "sci-fi"],
        "keywords": ["magic", "apocalypse", "survival", "catastrophe"],
        "description": "Three women navigate a broken, seismic-shifting world where magic is both feared and necessary.",
    },
    {
        "title": "The Color of Magic",
        "author": "Terry Pratchett",
        "genres": ["fantasy", "humor"],
        "keywords": ["comedy", "wizards", "magic", "adventure"],
        "description": "An inept wizard serves as a guide for the Discworld's very first tourist.",
    },
    {
        "title": "American Gods",
        "author": "Neil Gaiman",
        "genres": ["fantasy", "mystery"],
        "keywords": ["mythology", "gods", "road trip", "magic"],
        "description": "An ex-convict becomes the bodyguard for a mysterious man who is secretly an ancient god.",
    },
    {
        "title": "A Game of Thrones",
        "author": "George R. R. Martin",
        "genres": ["fantasy", "fiction"],
        "keywords": ["politics", "dragons", "war", "betrayal"],
        "description": "Noble families vie for control of the Iron Throne in a treacherous, magic-tinged kingdom.",
    },
    {
        "title": "The Blade Itself",
        "author": "Joe Abercrombie",
        "genres": ["fantasy", "fiction"],
        "keywords": ["grimdark", "war", "magic", "anti-hero"],
        "description": "A barbarian, a crippled inquisitor, and a vain nobleman find their fates intertwined.",
    },
    {
        "title": "Words of Radiance",
        "author": "Brandon Sanderson",
        "genres": ["fantasy", "adventure"],
        "keywords": ["magic", "war", "knights", "destiny"],
        "description": "The struggle for survival continues as ancient magical orders begin to reawaken.",
    },
    {
        "title": "Warbreaker",
        "author": "Brandon Sanderson",
        "genres": ["fantasy", "romance"],
        "keywords": ["magic", "gods", "sisters", "politics"],
        "description": "Two princesses navigate a kingdom where breath is magic and colors hold power.",
    },
    {
        "title": "Stardust",
        "author": "Neil Gaiman",
        "genres": ["fantasy", "adventure", "romance"],
        "keywords": ["magic", "stars", "quest", "witches"],
        "description": "A young man promises to retrieve a fallen star to win the heart of his beloved.",
    },
    {
        "title": "Foundation",
        "author": "Isaac Asimov",
        "genres": ["sci-fi", "classics"],
        "keywords": ["space", "future", "empire", "psychohistory"],
        "description": "A mathematician creates a foundational society to preserve human knowledge through a galactic dark age.",
    },
    {
        "title": "I, Robot",
        "author": "Isaac Asimov",
        "genres": ["sci-fi", "classics"],
        "keywords": ["robots", "ai", "ethics", "future"],
        "description": "A deeply influential collection of interconnected stories exploring the three laws of robotics.",
    },
    {
        "title": "Do Androids Dream of Electric Sheep?",
        "author": "Philip K. Dick",
        "genres": ["sci-fi", "classics"],
        "keywords": ["androids", "cyberpunk", "bounty hunter", "humanity"],
        "description": "A bounty hunter tracks down rogue androids in a post-apocalyptic, dust-covered Earth.",
    },
    {
        "title": "Snow Crash",
        "author": "Neal Stephenson",
        "genres": ["sci-fi", "cyberpunk"],
        "keywords": ["cyberpunk", "virtual reality", "hackers", "action"],
        "description": "A pizza delivery driver and hacker explores a virtual metaverse to stop a dangerous new drug.",
    },
    {
        "title": "Hyperion",
        "author": "Dan Simmons",
        "genres": ["sci-fi", "fantasy"],
        "keywords": ["space", "time travel", "pilgrims", "mystery"],
        "description": "Seven pilgrims share their tales on a journey toward an enigmatic, time-bending tomb.",
    },
    {
        "title": "Leviathan Wakes",
        "author": "James S. A. Corey",
        "genres": ["sci-fi", "mystery"],
        "keywords": ["space opera", "detective", "conspiracy", "aliens"],
        "description": "A missing girl links a hardened detective and a spaceship captain to a system-wide conspiracy.",
    },
    {
        "title": "The Three-Body Problem",
        "author": "Cixin Liu",
        "genres": ["sci-fi", "mystery"],
        "keywords": ["aliens", "physics", "first contact", "survival"],
        "description": "Humanity faces a looming crisis as contact is made with a struggling, distant alien civilization.",
    },
    {
        "title": "The Dark Forest",
        "author": "Cixin Liu",
        "genres": ["sci-fi", "thriller"],
        "keywords": ["space", "aliens", "strategy", "survival"],
        "description": "Earth scrambles to prepare a defense against an impending alien fleet out in the dark forest of space.",
    },
    {
        "title": "Project Hail Mary",
        "author": "Andy Weir",
        "genres": ["sci-fi", "adventure"],
        "keywords": ["space", "science", "survival", "friendship"],
        "description": "A lone astronaut wakes up with amnesia and must save a dying Earth using science and unusual friendship.",
    },
    {
        "title": "Red Rising",
        "author": "Pierce Brown",
        "genres": ["sci-fi", "dystopia", "action"],
        "keywords": ["mars", "rebellion", "class", "survival"],
        "description": "A miner infiltrates the elite ruling class of Mars to dismantle a brutal, color-coded society from the inside.",
    },
    {
        "title": "The Da Vinci Code",
        "author": "Dan Brown",
        "genres": ["mystery", "thriller"],
        "keywords": ["conspiracy", "art", "religion", "puzzle"],
        "description": "A symbologist unravels a historical conspiracy hidden within the works of Leonardo da Vinci.",
    },
    {
        "title": "Gone Girl",
        "author": "Gillian Flynn",
        "genres": ["mystery", "thriller"],
        "keywords": ["marriage", "disappearance", "secrets", "psychological"],
        "description": "A husband becomes the prime suspect when his wife mysteriously disappears on their anniversary.",
    },
    {
        "title": "The Silent Patient",
        "author": "Alex Michaelides",
        "genres": ["mystery", "thriller"],
        "keywords": ["psychology", "murder", "silence", "secrets"],
        "description": "A criminal psychotherapist becomes obsessed with a patient who shot her husband and hasn't spoken since.",
    },
    {
        "title": "The Girl on the Train",
        "author": "Paula Hawkins",
        "genres": ["mystery", "thriller"],
        "keywords": ["murder", "alcoholism", "memory", "secrets"],
        "description": "A commuter becomes entangled in a missing persons investigation intertwined with her past.",
    },
    {
        "title": "Before I Go to Sleep",
        "author": "S. J. Watson",
        "genres": ["mystery", "thriller"],
        "keywords": ["amnesia", "memory", "marriage", "secrets"],
        "description": "A woman wakes up every day with no memories and soon realizes her life might be built on a lie.",
    },
    {
        "title": "The Guest List",
        "author": "Lucy Foley",
        "genres": ["mystery", "thriller"],
        "keywords": ["wedding", "island", "murder", "secrets"],
        "description": "A lavish island wedding turns dark when an unexpected body is discovered.",
    },
    {
        "title": "Big Little Lies",
        "author": "Liane Moriarty",
        "genres": ["mystery", "fiction"],
        "keywords": ["mothers", "school", "secrets", "murder"],
        "description": "A seemingly perfect community unravels as playground gossip escalates into a murder investigation.",
    },
    {
        "title": "And Then There Were None",
        "author": "Agatha Christie",
        "genres": ["mystery", "classics", "thriller"],
        "keywords": ["island", "murder", "strangers", "survival"],
        "description": "Ten strangers are lured to an isolated island, only to be killed off one by one.",
    },
    {
        "title": "The Cuckoo's Calling",
        "author": "Robert Galbraith",
        "genres": ["mystery", "thriller"],
        "keywords": ["detective", "murder", "london", "investigation"],
        "description": "A struggling private investigator looks into the suspicious death of a supermodel in London.",
    },
    {
        "title": "Sharp Objects",
        "author": "Gillian Flynn",
        "genres": ["mystery", "thriller"],
        "keywords": ["journalism", "family", "hometown", "secrets"],
        "description": "A reporter returns to her troubled hometown to cover the murders of two young girls.",
    },
    {
        "title": "Dark Places",
        "author": "Gillian Flynn",
        "genres": ["mystery", "thriller"],
        "keywords": ["murder", "cult", "family", "secrets"],
        "description": "A woman confronts the horrific reality of her family's massacre years after her testimony imprisoned her brother.",
    },
    {
        "title": "The Turn of the Key",
        "author": "Ruth Ware",
        "genres": ["mystery", "thriller"],
        "keywords": ["nanny", "haunted house", "secrets", "murder"],
        "description": "A live-in nanny's dream job in the Scottish Highlands turns into a nightmare when a child is found dead.",
    },
    {
        "title": "In the Woods",
        "author": "Tana French",
        "genres": ["mystery", "thriller"],
        "keywords": ["detective", "dublin", "memory", "murder"],
        "description": "A detective investigates a murder in the same woods where his childhood friends mysteriously vanished.",
    },
    {
        "title": "The Woman in the Window",
        "author": "A. J. Finn",
        "genres": ["mystery", "thriller"],
        "keywords": ["agoraphobia", "secrets", "neighbors", "paranoia"],
        "description": "An agoraphobic woman believes she has witnessed a crime in her neighbor's house, but nobody believes her.",
    },
    {
        "title": "Outlander",
        "author": "Diana Gabaldon",
        "genres": ["romance", "historical", "fantasy"],
        "keywords": ["time travel", "scotland", "love", "war"],
        "description": "A time-traveling 20th-century nurse finds herself torn between two centuries and two loves.",
    },
    {
        "title": "The Hating Game",
        "author": "Sally Thorne",
        "genres": ["romance", "comedy"],
        "keywords": ["enemies to lovers", "workplace", "humor", "love"],
        "description": "Two fiercely competitive executive assistants discover the fine line between love and hate.",
    },
    {
        "title": "Red, White & Royal Blue",
        "author": "Casey McQuiston",
        "genres": ["romance", "ya", "comedy"],
        "keywords": ["royalty", "politics", "enemies to lovers", "lgbtq"],
        "description": "The First Son of the United States and a British prince turn a fake friendship into a real romance.",
    },
    {
        "title": "Beach Read",
        "author": "Emily Henry",
        "genres": ["romance", "fiction"],
        "keywords": ["writers", "summer", "love", "enemies to lovers"],
        "description": "Two rival authors spend a summer as neighbors and swap writing genres to break their writer's block.",
    },
    {
        "title": "Book Lovers",
        "author": "Emily Henry",
        "genres": ["romance", "fiction"],
        "keywords": ["books", "publishing", "enemies to lovers", "sisters"],
        "description": "A cutthroat literary agent runs into her rival editor during a small-town summer vacation.",
    },
    {
        "title": "It Ends with Us",
        "author": "Colleen Hoover",
        "genres": ["romance", "fiction"],
        "keywords": ["love", "heartbreak", "abuse", "choices"],
        "description": "A woman forms a new relationship while grappling with her past and a suddenly returned first love.",
    },
    {
        "title": "The Kiss Quotient",
        "author": "Helen Hoang",
        "genres": ["romance", "fiction"],
        "keywords": ["autism", "escort", "fake dating", "love"],
        "description": "An econometrician with Asperger's hires a male escort to help her figure out how to date.",
    },
    {
        "title": "The Love Hypothesis",
        "author": "Ali Hazelwood",
        "genres": ["romance", "comedy"],
        "keywords": ["science", "academia", "fake dating", "humor"],
        "description": "A Ph.D. candidate fakes a relationship with a biology professor, leading to unexpected chemistry.",
    },
    {
        "title": "The Rosie Project",
        "author": "Graeme Simsion",
        "genres": ["romance", "comedy", "fiction"],
        "keywords": ["genetics", "autism", "love", "humor"],
        "description": "A brilliant but socially awkward genetics professor sets out to scientifically find a wife.",
    },
    {
        "title": "Seven Husbands of Evelyn Hugo",
        "author": "Taylor Jenkins Reid",
        "genres": ["romance", "historical", "fiction"],
        "keywords": ["hollywood", "fame", "secrets", "lgbtq"],
        "description": "An aging Hollywood icon finally reveals the glamorous, scandalous truth about her life and loves.",
    },
    {
        "title": "Normal People",
        "author": "Sally Rooney",
        "genres": ["romance", "fiction"],
        "keywords": ["love", "class", "ireland", "coming-of-age"],
        "description": "A complicated, shifting relationship between two Irish teenagers as they move from school to university.",
    },
    {
        "title": "Bridgerton: The Duke and I",
        "author": "Julia Quinn",
        "genres": ["romance", "historical"],
        "keywords": ["london", "fake dating", "high society", "love"],
        "description": "A faux courtship between a duke and a debutante blossoms into unexpected genuine affection.",
    },
    {
        "title": "People We Meet on Vacation",
        "author": "Emily Henry",
        "genres": ["romance", "comedy"],
        "keywords": ["friends to lovers", "travel", "humor", "summer"],
        "description": "Two best friends try to mend their broken relationship with one last summer trip together.",
    },
    {
        "title": "Love on the Brain",
        "author": "Ali Hazelwood",
        "genres": ["romance", "comedy"],
        "keywords": ["science", "academia", "enemies to lovers", "humor"],
        "description": "A neuroscientist must co-lead a project with her old nemesis, sparking more than just professional tension.",
    },
    {
        "title": "Twilight",
        "author": "Stephenie Meyer",
        "genres": ["ya", "fantasy", "romance"],
        "keywords": ["vampires", "werewolves", "first love", "supernatural"],
        "description": "A teenage girl moves to a rainy town and falls for a mysterious, sparkling vampire.",
    },
    {
        "title": "Divergent",
        "author": "Veronica Roth",
        "genres": ["ya", "dystopia", "sci-fi"],
        "keywords": ["factions", "survival", "rebellion", "identity"],
        "description": "In a divided society, a girl discovers she fits into no single faction and must hide her nature.",
    },
    {
        "title": "The Maze Runner",
        "author": "James Dashner",
        "genres": ["ya", "dystopia", "sci-fi"],
        "keywords": ["amnesia", "maze", "survival", "mystery"],
        "description": "A boy wakes up with no memory in the center of a deadly, ever-changing labyrinth.",
    },
    {
        "title": "Six of Crows",
        "author": "Leigh Bardugo",
        "genres": ["ya", "fantasy"],
        "keywords": ["heist", "magic", "outcasts", "gangs"],
        "description": "Six dangerous outcasts attempt an impossible heist in a magical, treacherous city.",
    },
    {
        "title": "Shadow and Bone",
        "author": "Leigh Bardugo",
        "genres": ["ya", "fantasy", "romance"],
        "keywords": ["magic", "war", "darkness", "destiny"],
        "description": "An orphan discovers a hidden power that could save her war-torn country from literal darkness.",
    },
    {
        "title": "The Perks of Being a Wallflower",
        "author": "Stephen Chbosky",
        "genres": ["ya", "fiction"],
        "keywords": ["coming-of-age", "friendship", "high school", "mental health"],
        "description": "An introverted high school freshman documents his experiences with friendship, love, and trauma.",
    },
    {
        "title": "Looking for Alaska",
        "author": "John Green",
        "genres": ["ya", "fiction", "romance"],
        "keywords": ["boarding school", "friendship", "grief", "first love"],
        "description": "A boy searches for the 'Great Perhaps' at a boarding school, where he meets an unforgettable girl.",
    },
    {
        "title": "The Giver",
        "author": "Lois Lowry",
        "genres": ["ya", "dystopia", "classics"],
        "keywords": ["memories", "society", "conformity", "rebellion"],
        "description": "A boy inherits the past memories of a seemingly perfect but deeply sterile society.",
    },
    {
        "title": "The Outsiders",
        "author": "S. E. Hinton",
        "genres": ["ya", "classics", "fiction"],
        "keywords": ["gangs", "brothers", "class", "coming-of-age"],
        "description": "Two rival teenage groups, the Greasers and the Socs, clash in a story of loyalty and strife.",
    },
    {
        "title": "Catching Fire",
        "author": "Suzanne Collins",
        "genres": ["ya", "dystopia", "sci-fi"],
        "keywords": ["survival", "rebellion", "games", "hope"],
        "description": "Sparks of rebellion ignite as former victors are forced back into a deadly arena.",
    },
    {
        "title": "A Court of Thorns and Roses",
        "author": "Sarah J. Maas",
        "genres": ["ya", "fantasy", "romance"],
        "keywords": ["fae", "magic", "beast", "love"],
        "description": "A huntress is taken to a magical realm as punishment, where her captor becomes her fierce protector.",
    },
    {
        "title": "Cinder",
        "author": "Marissa Meyer",
        "genres": ["ya", "sci-fi", "fairy tale"],
        "keywords": ["cyborg", "plague", "prince", "cinderella"],
        "description": "A teenage cyborg mechanic in a futuristic city gets tangled in intergalactic royalty and a deadly plague.",
    },
    {
        "title": "The Book Thief",
        "author": "Markus Zusak",
        "genres": ["ya", "historical", "fiction"],
        "keywords": ["wwii", "death", "books", "survival"],
        "description": "Narrated by Death, a young girl finds solace by stealing books in Nazi Germany.",
    },
    {
        "title": "Eleanor & Park",
        "author": "Rainbow Rowell",
        "genres": ["ya", "romance", "fiction"],
        "keywords": ["first love", "music", "misfits", "coming-of-age"],
        "description": "Two teenage misfits bond over comic books and mixtapes in 1986.",
    },
    {
        "title": "Becoming",
        "author": "Michelle Obama",
        "genres": ["non-fiction", "memoir"],
        "keywords": ["politics", "family", "inspiration", "history"],
        "description": "The deeply personal memoir of the former First Lady of the United States.",
    },
    {
        "title": "Born a Crime",
        "author": "Trevor Noah",
        "genres": ["non-fiction", "memoir", "humor"],
        "keywords": ["apartheid", "family", "comedy", "race"],
        "description": "A comedian's stories of his South African childhood, born during the twilight of apartheid.",
    },
    {
        "title": "The Glass Castle",
        "author": "Jeannette Walls",
        "genres": ["non-fiction", "memoir"],
        "keywords": ["family", "poverty", "resilience", "childhood"],
        "description": "A remarkable memoir of resilience and redemption in a deeply dysfunctional yet vibrant family.",
    },
    {
        "title": "Wild",
        "author": "Cheryl Strayed",
        "genres": ["non-fiction", "memoir", "adventure"],
        "keywords": ["hiking", "grief", "healing", "nature"],
        "description": "A woman’s solo hike along the Pacific Crest Trail becomes a journey of healing from profound grief.",
    },
    {
        "title": "Into the Wild",
        "author": "Jon Krakauer",
        "genres": ["non-fiction", "adventure", "biography"],
        "keywords": ["nature", "survival", "alaska", "isolation"],
        "description": "The true story of a young man who left society behind to live in the Alaskan wilderness.",
    },
    {
        "title": "In Cold Blood",
        "author": "Truman Capote",
        "genres": ["non-fiction", "true crime", "classics"],
        "keywords": ["murder", "investigation", "psychology", "kansas"],
        "description": "A chilling, meticulously researched account of a senseless quadruple murder in Kansas.",
    },
    {
        "title": "Outliers",
        "author": "Malcolm Gladwell",
        "genres": ["non-fiction", "psychology"],
        "keywords": ["success", "society", "culture", "opportunity"],
        "description": "An investigation into what makes high achievers different, looking beyond intelligence to hidden advantages.",
    },
    {
        "title": "Quiet",
        "author": "Susan Cain",
        "genres": ["non-fiction", "psychology"],
        "keywords": ["introverts", "society", "personality", "culture"],
        "description": "An impassioned argument highlighting the undervalued power of introverts in an extroverted world.",
    },
    {
        "title": "A Brief History of Time",
        "author": "Stephen Hawking",
        "genres": ["non-fiction", "science"],
        "keywords": ["physics", "cosmos", "time", "space"],
        "description": "A landmark volume in science writing exploring the depths and mysteries of the universe.",
    },
    {
        "title": "The Subtle Art of Not Giving a F*ck",
        "author": "Mark Manson",
        "genres": ["non-fiction", "self-help", "humor"],
        "keywords": ["happiness", "philosophy", "honesty", "values"],
        "description": "A counterintuitive approach to living a good life, focusing on embracing our flaws and limitations.",
    },
    {
        "title": "Braiding Sweetgrass",
        "author": "Robin Wall Kimmerer",
        "genres": ["non-fiction", "nature", "science"],
        "keywords": ["indigenous", "botany", "environment", "wisdom"],
        "description": "A botanist explores the beautiful intersection of scientific knowledge and Indigenous wisdom.",
    },
    {
        "title": "Man's Search for Meaning",
        "author": "Viktor E. Frankl",
        "genres": ["non-fiction", "psychology", "memoir"],
        "keywords": ["holocaust", "purpose", "survival", "philosophy"],
        "description": "A profound memoir of life in Nazi death camps and a meditation on finding meaning in suffering.",
    },
    {
        "title": "Thinking in Systems",
        "author": "Donella H. Meadows",
        "genres": ["non-fiction", "science", "psychology"],
        "keywords": ["systems", "society", "philosophy", "environment"],
        "description": "A brilliant primer on systems thinking to understand the complex world around us.",
    },
    {
        "title": "The Body Keeps the Score",
        "author": "Bessel van der Kolk",
        "genres": ["non-fiction", "psychology", "science"],
        "keywords": ["trauma", "healing", "body", "mind"],
        "description": "An exploration of trauma's profound effects on the body and pathways to recovery.",
    },
    {
        "title": "The Kite Runner",
        "author": "Khaled Hosseini",
        "genres": ["fiction", "historical"],
        "keywords": ["friendship", "redemption", "war", "afghanistan"],
        "description": "An Afghan boy seeks redemption after betraying his childhood friend during tumultuous times.",
    },
    {
        "title": "The Alchemist",
        "author": "Paulo Coelho",
        "genres": ["fiction", "fantasy"],
        "keywords": ["quest", "destiny", "philosophy", "journey"],
        "description": "An Andalusian shepherd boy journeys trying to find a worldly treasure and ends up discovering himself.",
    },
    {
        "title": "Life of Pi",
        "author": "Yann Martel",
        "genres": ["fiction", "adventure"],
        "keywords": ["survival", "tiger", "ocean", "faith"],
        "description": "A young boy survives a shipwreck but finds himself in a lifeboat with a Bengal tiger.",
    },
    {
        "title": "The Help",
        "author": "Kathryn Stockett",
        "genres": ["fiction", "historical"],
        "keywords": ["civil rights", "maids", "friendship", "south"],
        "description": "Three extraordinary women build an unlikely friendship across race lines in 1960s Mississippi.",
    },
    {
        "title": "All the Light We Cannot See",
        "author": "Anthony Doerr",
        "genres": ["fiction", "historical"],
        "keywords": ["wwii", "blindness", "radio", "survival"],
        "description": "The paths of a blind French girl and a German boy collide in occupied France as both try to survive WWII.",
    },
    {
        "title": "Where the Crawdads Sing",
        "author": "Delia Owens",
        "genres": ["fiction", "mystery", "romance"],
        "keywords": ["nature", "marsh", "murder", "coming-of-age"],
        "description": "A quiet marsh girl becomes the prime suspect in the murder of a beloved local man.",
    },
    {
        "title": "A Man Called Ove",
        "author": "Fredrik Backman",
        "genres": ["fiction", "comedy"],
        "keywords": ["grumpy", "neighbors", "grief", "friendship"],
        "description": "A grumpy, strict elderly man finds his life turned upside down by a boisterous young family next door.",
    },
    {
        "title": "The Midnight Library",
        "author": "Matt Haig",
        "genres": ["fiction", "fantasy"],
        "keywords": ["choices", "regret", "parallel lives", "hope"],
        "description": "A magical library allows a woman to explore the different paths her life could have taken.",
    },
    {
        "title": "Little Fires Everywhere",
        "author": "Celeste Ng",
        "genres": ["fiction", "mystery"],
        "keywords": ["suburbs", "family", "secrets", "motherhood"],
        "description": "A picture-perfect suburban family becomes dangerously entangled with a mysterious artist and her daughter.",
    },
    {
        "title": "The Secret History",
        "author": "Donna Tartt",
        "genres": ["fiction", "mystery", "thriller"],
        "keywords": ["college", "classics", "murder", "secrets"],
        "description": "A group of eccentric classics students at a New England college pushes the boundaries of morality to fatal results.",
    },
    {
        "title": "A Thousand Splendid Suns",
        "author": "Khaled Hosseini",
        "genres": ["fiction", "historical"],
        "keywords": ["women", "afghanistan", "survival", "friendship"],
        "description": "Two generations of Afghan women are brought together by war, loss, and enduring strength.",
    },
    {
        "title": "Water for Elephants",
        "author": "Sara Gruen",
        "genres": ["fiction", "romance", "historical"],
        "keywords": ["circus", "animals", "love", "depression era"],
        "description": "A veterinary student finds a new life and forbidden love in a traveling circus during the Great Depression.",
    },
    {
        "title": "The Secret Life of Bees",
        "author": "Sue Monk Kidd",
        "genres": ["fiction", "historical", "ya"],
        "keywords": ["sisters", "healing", "race", "south"],
        "description": "A young girl runs away to live with eccentric beekeeping sisters in 1960s South Carolina.",
    },
    {
        "title": "The Goldfinch",
        "author": "Donna Tartt",
        "genres": ["fiction", "mystery"],
        "keywords": ["art", "grief", "orphans", "betrayal"],
        "description": "A boy survives an explosion that kills his mother and clings to a small painting that drags him into the underworld.",
    },
    {
        "title": "Beartown",
        "author": "Fredrik Backman",
        "genres": ["fiction", "thriller"],
        "keywords": ["hockey", "community", "scandal", "secrets"],
        "description": "A violent act threatens to tear apart a small, desperate town obsessed with its junior hockey team.",
    },
    {
        "title": "Anxious People",
        "author": "Fredrik Backman",
        "genres": ["fiction", "comedy", "mystery"],
        "keywords": ["hostage", "apartment", "anxiety", "humor"],
        "description": "A chaotic bank robbery goes wrong, turning an apartment viewing into a heartwarming hostage situation.",
    },
    {
        "title": "Conversations with Friends",
        "author": "Sally Rooney",
        "genres": ["fiction", "romance"],
        "keywords": ["poetry", "affair", "friendship", "youth"],
        "description": "Two college students become unexpectedly entangled with an older, married couple in Dublin.",
    },
    {
        "title": "The Vanishing Half",
        "author": "Brit Bennett",
        "genres": ["fiction", "historical"],
        "keywords": ["twins", "identity", "race", "family"],
        "description": "Twin sisters grow apart over decades as one stays in their small, Southern black community and the other passes for white.",
    },
]

